version: '3.9'

services:
  db:
    image: postgres:13.3
    container_name: hotel-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=hotel
      - POSTGRES_USER=user_1
      - POSTGRES_PASSWORD=12345
    volumes:
      - db:/var/lib/postgres

volumes:
  db:




