#work with dc.env for environment
version: '2.7'

services:
  # 4 - backend
  hotel-server_service:
    build:
      context: ..
      dockerfile: docker/Hotel_server.Dockerfile
    container_name: hotel-server
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - dc.env
#    networks:
#      - net

  # 5 - frontend
  hotel-ui_service:
    build:
      context: ..
      dockerfile: docker/Hotel_ui.Dockerfile
    container_name: hotel-ui
    ports:
      - "8086:8086"
    restart: always
#    networks:
#      - net

  # 6 - kafka-configuration
  hotel-kafka_service:
    build:
      context: ..
      dockerfile: docker/Hotel_kafka.Dockerfile
    container_name: hotel-kafka
    ports:
      - "9095:9095"
    restart: always
    env_file:
      - dc.env
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
#    networks:
#      - net

  # 7 - listener
  hotel-room_manager_service:
    build:
      context: ..
      dockerfile: docker/Hotel_room_manager.Dockerfile
    container_name: hotel-room-manager
    ports:
      - "8087:8087"
    restart: always
    env_file:
      - dc.env
#    networks:
#      - net


volumes:
  db:

#networks:
#  net:



