version: '3.9'

services:
  db:
    image: postgres:13.3
    container_name: hotel-postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - dc.env
    volumes:
      - db:/var/lib/postgres
#    networks:
#      - net

volumes:
  db:

#networks:
#  net:





