#work with dc.env for environment
version: '2.7'

services:
  # 1 - backend
  hotel-server_service:
    build:
      context: ..
      dockerfile: docker/Hotel_server.Dockerfile
    container_name: hotel-server
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - dc.env
#    networks:
#      - net

  # 2 - frontend
  hotel-ui_service:
    build:
      context: ..
      dockerfile: docker/Hotel_ui.Dockerfile
    container_name: hotel-ui
    ports:
      - "8086:8086"
    restart: always
#    networks:
#      - net


  # 3 - activeMQ
  activemq-service:
    image: rmohr/activemq:5.15.9-alpine
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    restart: always
#    networks:
#      - net

  # 4 - activemq-configuration
  hotel-acivemq_service:
    build:
      context: ..
      dockerfile: docker/Hotel_activemq.Dockerfile
    container_name: hotel-acivemq
    ports:
      - "9095:9095"
    restart: always
#    networks:
#      - net

  # 5 - listener
  hotel-room_manager_service:
    build:
      context: ..
      dockerfile: docker/Hotel_room_manager.Dockerfile
    container_name: hotel-room-manager
    ports:
      - "8087:8087"
    restart: always
    env_file:
      - dc.env
#    networks:
#      - net


volumes:
  db:

#networks:
#  net:



